AWSTemplateFormatVersion: 2010-09-09
Description: Create Minimal requirements for InfraPipe
Parameters:
  # Set the name of your AWS ENVIRONMENT here: DEV/QA/PROD
  InfraPipeEnv:
    Type: String
    Default: DEV
    Description: Please enter the environment alias in all UPPERCASE.
  InfraPipeIamUsername:
    Type: String
    Default: terraform
    Description: Please enter the name of IAM user for the pipeline in all lowercase.
  InfraPipeIamPath:
    Type: String
    Default: pipeline
    Description: Please enter the path for IAM roles without beginning or ending with '/'.
  InfraPipeSsmPath:
    Type: String
    Default: security/pipeline
    Description: Please enter the path for SSM parameters without beginning or ending '/'.
Resources:
  # Create Infrapipe user
  InfraPipeIamUser:
    Type: 'AWS::IAM::User'
    Properties:
      Path: !Sub '/${InfraPipeIamPath}/'
      UserName: !Ref InfraPipeIamUsername
      Tags:
        - Key: Name
          Value: !Ref InfraPipeIamUsername
  # Grant read-only SSM permissions to Infrapipe User
  InfraPipeIamUserPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: InfraPipeIamUserPolicy-SSMReadonly
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: ssm:GetParameters
            Effect: Allow
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${InfraPipeSsmPath}/*'
      Users:
        - !Ref InfraPipeIamUser
  # Grant Full Admin Access to Infrapipe role
  InfraPipeIamRolePolicyFullAdmin:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: InfraPipeIamRolePolicy-FullAdmin
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref InfraPipeIamRole
  # Allow Infrapipe user to assume pipeline role
  InfraPipeIamRolePolicyAssumePipelineRole:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: InfraPipeIamRolePolicy-AssumePipelineRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${InfraPipeIamPath}/*'
      Users:
        - !Ref InfraPipeIamUser
  InfraPipeIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${InfraPipeIamUsername}-${InfraPipeEnv}-role'
      Path: !Sub '/${InfraPipeIamPath}/'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt InfraPipeIamUser.Arn
            Action:
              - 'sts:AssumeRole'
  InfraPipeTfStateS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'tfstate-infrapipe-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # Enable bucket versioning to allow reverting back to previous TF state
      VersioningConfiguration:
        Status: Enabled
      # Deny public access to bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
  InfraPipeSSMParamS3BucketName:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: Name of the S3 bucket storing Terraform state
      Name: !Sub '/${InfraPipeSsmPath}/${InfraPipeEnv}/AWS_TFSTATE_S3_BUCKET'
      Type: String
      Value: !Ref InfraPipeTfStateS3Bucket
  InfraPipeSSMParamS3BucketKey:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: Key of the S3 bucket storing Terraform state
      Name: !Sub '/${InfraPipeSsmPath}/${InfraPipeEnv}/AWS_TFSTATE_S3_KEY'
      Type: String
      Value: terraform.tfstate
  InfraPipeSSMParamPipelineRole:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: Name of Pipeline IAM Role
      Name: !Sub '/${InfraPipeSsmPath}/${InfraPipeEnv}/AWS_ASSUME_ROLE_ARN'
      Type: String
      Value: !GetAtt InfraPipeIamRole.Arn
