style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/shiftsecurityleft/infrapipe/infrapipe.git
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
